mybatis:
  config-location: classpath:Mybatis/mybatis-config.xml
  mapper-locations: classpath:Mybatis/mapper/*.xml

markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

shiro-redis:
    enabled: true
    redis-manager:
        host: 127.0.0.1:6379

spring:
  redis:
    host: 127.0.0.1
    port: 6379


